import { neon } from "@neondatabase/serverless";

export function getDb() {
  if (!process.env.NEON_DATABASE_URL) {
    throw new Error("NEON_DATABASE_URL env variable is not set");
  }
  return neon(process.env.NEON_DATABASE_URL);
}

export async function initSchema(sql) {
  // ── Core tables ─────────────────────────────────────────────────
  await sql`
    CREATE TABLE IF NOT EXISTS questions (
      id            SERIAL PRIMARY KEY,
      lc_number     INTEGER NOT NULL UNIQUE,
      name          TEXT NOT NULL,
      url           TEXT NOT NULL,
      topic         TEXT NOT NULL,
      difficulty    TEXT NOT NULL CHECK (difficulty IN ('Easy','Medium','Hard')),
      section       TEXT NOT NULL,
      section_order INTEGER NOT NULL DEFAULT 99,
      tags          TEXT[] DEFAULT '{}',
      created_at    TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  // ── Users table ─────────────────────────────────────────────────
  await sql`
    CREATE TABLE IF NOT EXISTS users (
      id         SERIAL PRIMARY KEY,
      email      TEXT NOT NULL UNIQUE,
      clerk_id   TEXT,
      name       TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  // ── Progress table (original, single-user) ───────────────────────
  await sql`
    CREATE TABLE IF NOT EXISTS progress (
      id          SERIAL PRIMARY KEY,
      lc_number   INTEGER NOT NULL UNIQUE REFERENCES questions(lc_number) ON DELETE CASCADE,
      is_done     BOOLEAN DEFAULT FALSE,
      solution    TEXT DEFAULT '',
      notes       TEXT DEFAULT '',
      updated_at  TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  // ── Safe column migrations ───────────────────────────────────────
  try {
    await sql`ALTER TABLE questions ADD COLUMN IF NOT EXISTS similar_problems INTEGER[] DEFAULT NULL`;
    await sql`ALTER TABLE questions ADD COLUMN IF NOT EXISTS companies_asked TEXT[] DEFAULT '{}'`;
  } catch (e) {
    if (!e.message.includes("already exists")) {
    }
  }

  try {
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS needs_review BOOLEAN DEFAULT FALSE`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS time_complexity TEXT DEFAULT ''`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS space_complexity TEXT DEFAULT ''`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS srs_interval_index INTEGER DEFAULT 0`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS srs_last_reviewed_at TIMESTAMPTZ DEFAULT NULL`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS ai_analysis TEXT DEFAULT ''`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS solved_at TIMESTAMPTZ DEFAULT NULL`;
  } catch (e) {
  }

  // ── Per-user progress migration ──────────────────────────────────
  // 1. Add user_email column (defaults existing rows to the original user)
  // 2. Drop the old single-column UNIQUE constraint on lc_number
  // 3. Add a composite UNIQUE on (lc_number, user_email) for multi-user support
  try {
    await sql`
      ALTER TABLE progress
      ADD COLUMN IF NOT EXISTS user_email TEXT NOT NULL DEFAULT ''
    `;
  } catch (e) {
  }

  // ── Users table migrations (each in its own try so one failure doesn't block the rest) ──
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS is_subscribed BOOLEAN DEFAULT FALSE`; } catch (e) {}
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS reminders_enabled BOOLEAN DEFAULT FALSE`; } catch (e) {}
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS reminder_email TEXT`; } catch (e) {}
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT`; } catch (e) {}

  try {
    // Drop old single-column unique constraint (name generated by Postgres)
    await sql`ALTER TABLE progress DROP CONSTRAINT IF EXISTS progress_lc_number_key`;
  } catch (e) {
    // Constraint may have already been dropped — ignore
  }

  try {
    await sql`
      DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'progress_lc_user_unique'
        ) THEN
          ALTER TABLE progress
            ADD CONSTRAINT progress_lc_user_unique UNIQUE (lc_number, user_email);
        END IF;
      END $$
    `;
  } catch (e) {
  }
}
