import { neon } from "@neondatabase/serverless";

export function getDb() {
  if (!process.env.NEON_DATABASE_URL) {
    throw new Error("NEON_DATABASE_URL env variable is not set");
  }
  return neon(process.env.NEON_DATABASE_URL);
}

export async function initSchema(sql) {
  // ── Core tables ─────────────────────────────────────────────────
  await sql`
    CREATE TABLE IF NOT EXISTS questions (
      id            SERIAL PRIMARY KEY,
      lc_number     INTEGER NOT NULL UNIQUE,
      name          TEXT NOT NULL,
      url           TEXT NOT NULL,
      topic         TEXT NOT NULL,
      difficulty    TEXT NOT NULL CHECK (difficulty IN ('Easy','Medium','Hard')),
      section       TEXT NOT NULL,
      section_order INTEGER NOT NULL DEFAULT 99,
      tags          TEXT[] DEFAULT '{}',
      created_at    TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  // ── Users table ─────────────────────────────────────────────────
  await sql`
    CREATE TABLE IF NOT EXISTS users (
      id         SERIAL PRIMARY KEY,
      email      TEXT NOT NULL UNIQUE,
      clerk_id   TEXT,
      name       TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  // ── Progress table (original, single-user) ───────────────────────
  await sql`
    CREATE TABLE IF NOT EXISTS progress (
      id          SERIAL PRIMARY KEY,
      lc_number   INTEGER NOT NULL UNIQUE REFERENCES questions(lc_number) ON DELETE CASCADE,
      is_done     BOOLEAN DEFAULT FALSE,
      solution    TEXT DEFAULT '',
      notes       TEXT DEFAULT '',
      updated_at  TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  // ── Safe column migrations ───────────────────────────────────────
  try {
    await sql`ALTER TABLE questions ADD COLUMN IF NOT EXISTS similar_problems INTEGER[] DEFAULT NULL`;
    await sql`ALTER TABLE questions ADD COLUMN IF NOT EXISTS companies_asked TEXT[] DEFAULT '{}'`;
    await sql`ALTER TABLE questions ADD COLUMN IF NOT EXISTS hint TEXT DEFAULT NULL`;
  } catch (e) {
    if (!e.message.includes("already exists")) {
    }
  }

  try {
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS needs_review BOOLEAN DEFAULT FALSE`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS time_complexity TEXT DEFAULT ''`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS space_complexity TEXT DEFAULT ''`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS srs_interval_index INTEGER DEFAULT 0`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS srs_last_reviewed_at TIMESTAMPTZ DEFAULT NULL`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS ai_analysis TEXT DEFAULT ''`;
    await sql`ALTER TABLE progress ADD COLUMN IF NOT EXISTS solved_at TIMESTAMPTZ DEFAULT NULL`;
  } catch (e) {
  }

  // ── Per-user progress migration ──────────────────────────────────
  // 1. Add user_email column (defaults existing rows to the original user)
  // 2. Drop the old single-column UNIQUE constraint on lc_number
  // 3. Add a composite UNIQUE on (lc_number, user_email) for multi-user support
  try {
    await sql`
      ALTER TABLE progress
      ADD COLUMN IF NOT EXISTS user_email TEXT NOT NULL DEFAULT ''
    `;
  } catch (e) {
  }

  // users table migrations — each isolated so one failure doesn't block the rest
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS is_subscribed BOOLEAN DEFAULT FALSE`; } catch (e) {}
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS reminders_enabled BOOLEAN DEFAULT FALSE`; } catch (e) {}
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS reminder_email TEXT`; } catch (e) {}
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT`; } catch (e) {}
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'USER'`; } catch (e) {}
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS clerk_name TEXT`; } catch (e) {}
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS last_active TIMESTAMPTZ`; } catch (e) {}
  try { await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS broadcast_unsubscribed BOOLEAN DEFAULT FALSE`; } catch (e) {}
  // Backfill: set last_active to created_at for existing users where it is null
  try { await sql`UPDATE users SET last_active = created_at WHERE last_active IS NULL`; } catch (e) {}
  // Backfill: copy name → clerk_name for existing users who don't have it yet
  try { await sql`UPDATE users SET clerk_name = name WHERE clerk_name IS NULL AND name IS NOT NULL`; } catch (e) {}

  try {
    // Drop old single-column unique constraint (name generated by Postgres)
    await sql`ALTER TABLE progress DROP CONSTRAINT IF EXISTS progress_lc_number_key`;
  } catch (e) {
    // Constraint may have already been dropped — ignore
  }

  try {
    await sql`
      DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'progress_lc_user_unique'
        ) THEN
          ALTER TABLE progress
            ADD CONSTRAINT progress_lc_user_unique UNIQUE (lc_number, user_email);
        END IF;
      END $$
    `;
  } catch (e) {
  }

  // ── Performance indexes ──────────────────────────────────────────────────
  try {
    await sql`CREATE INDEX IF NOT EXISTS idx_progress_user_email ON progress(user_email)`;
    await sql`CREATE INDEX IF NOT EXISTS idx_progress_lc_user ON progress(lc_number, user_email)`;
    await sql`CREATE INDEX IF NOT EXISTS idx_questions_section_order ON questions(section_order, lc_number)`;
    await sql`CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)`;
    // Covers night-reminder "solved today" filter (is_done + solved_at range scan)
    await sql`CREATE INDEX IF NOT EXISTS idx_progress_user_done_solved ON progress(user_email, solved_at) WHERE is_done = TRUE`;
    // Covers reminders "done count per user" aggregation
    await sql`CREATE INDEX IF NOT EXISTS idx_progress_user_is_done ON progress(user_email) WHERE is_done = TRUE`;
  } catch (e) { /* ignore — indexes may already exist */ }

  // ── AI rate-limiting table ───────────────────────────────────────────────
  try {
    await sql`
      CREATE TABLE IF NOT EXISTS ai_rate_limits (
        user_email   TEXT        NOT NULL,
        window_start TIMESTAMPTZ NOT NULL,
        count        INTEGER     NOT NULL DEFAULT 0,
        PRIMARY KEY (user_email, window_start)
      )
    `;
    await sql`CREATE INDEX IF NOT EXISTS idx_rate_limits_user ON ai_rate_limits(user_email)`;
    // Purge windows older than 1 hour to keep the table lean
    await sql`DELETE FROM ai_rate_limits WHERE window_start < NOW() - INTERVAL '1 hour'`;
  } catch (e) { /* ignore */ }
}
